### ISSUE TITLE
Image quality training: model object doesn't compile

### ISSUE THREAD

**Issue by cswingle** [gerlis22/CameraTrap#1]
I'm working through your workflow, and am running into issues trying to train a classifier for Good/Bad images using the [Step 2A code](https://github.com/gerlis22/CameraTrap/blob/main/Step_2_A_Model_Training_ImageQuality.R). On [line 83](https://github.com/gerlis22/CameraTrap/blob/e4751ebe58bc54fda3d4e248c8f312687d6f7912/Step_2_A_Model_Training_ImageQuality.R#L83) a model object is created using the `application_resnet50()` function. The next step is to compile it, but R is telling me it's not the proper object type:

```
Error in UseMethod("compile") :
no applicable method for 'compile' applied to an object of class "c('keras.src.models.functional.Functional',
'keras.models.functional.Functional', 'keras.src.ops.function.Function', 'keras.ops.function.Function',
'keras.src.models.model.Model', 'keras.models.model.Model', 'keras.src.backend.tensorflow.trainer.TensorFlowTrainer',
'keras.backend.tensorflow.trainer.TensorFlowTrainer', 'keras.src.trainers.trainer.Trainer', 'keras.trainers.trainer.Trainer',
'keras.src.layers.layer.Layer', 'keras.layers.layer.Layer', 'keras.src.backend.tensorflow.layer.TFLayer',
'keras.backend.tensorflow.layer.TFLayer', 'keras.src.backend.tensorflow.trackable.KerasAutoTrackable',
'keras.backend.tensorflow.trackable.KerasAutoTrackable', 'tensorflow.python.trackable.autotrackable.AutoTrackable',
'tensorflow.python.trackable.base.Trackable', 'keras.src.ops.operation.Operation', 'keras.ops.operation.Operation',
'keras.src.saving.keras_saveable.KerasSaveable', 'keras.saving.keras_saveable.KerasSaveable', 'python.builtin.object')
```

Quite a mouthful!

According to the docs, it looks like `compile()` is looking for a `keras.engine.training.Model` object.

`sessionInfo()` reports R 4.3.3, reticulate_1.38.0, tensorflow_2.16.0.9000, keras_2.15.0, generics_0.1.3, and compiler_4.3.3.

Thoughts?

**Comment by cswingle** [comment]
It looks like I didn't have the correct Keras version installed. Instead of using `install_tensorflow()`, I needed to use:

```
install.packages(keras)
library(keras)
install_keras()
```

I don't know why this made a difference because `sessionInfo()` still reports the same versions of the relevant packages, but now when I create the `model` object using `application_resnet50()` the class of the returned object includes `keras.engine.training.Model`.

Sorry for the noise!

**Comment by gerlis22** [comment]
@cswingle, thank you for letting us know about the issue. The new Keras package, [keras3](https://keras.io/keras_3/), is used with the most recent `tensorflow` package install, which creates issues with an older version of `keras`. Installing the `keras` package directly `keras::install_keras` fixes this issue.
